openapi: 3.0.0
info:
  title: 数据源管理 API
  description: 数据源集成功能的 REST API，支持 PostgreSQL 和文件上传
  version: 1.0.0
servers:
  - url: /api
    description: API 基础路径

paths:
  /datasources:
    get:
      summary: 获取所有数据源列表
      tags:
        - 数据源
      parameters:
        - name: skip
          in: query
          required: false
          schema:
            type: integer
            default: 0
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: 数据源列表
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/DataSource'
        '401':
          $ref: '#/components/responses/Unauthorized'

    post:
      summary: 创建新的 PostgreSQL 连接
      tags:
        - 数据源
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePostgresRequest'
      responses:
        '201':
          description: 数据源创建成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataSource'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /datasources/{id}:
    get:
      summary: 获取单个数据源详情
      tags:
        - 数据源
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: 数据源详情
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataSource'
        '404':
          $ref: '#/components/responses/NotFound'

    delete:
      summary: 删除数据源
      tags:
        - 数据源
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: 删除成功
        '404':
          $ref: '#/components/responses/NotFound'

  /datasources/{id}/test:
    post:
      summary: 测试数据源连接
      tags:
        - 数据源
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: 连接测试结果
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  error:
                    type: string
        '404':
          $ref: '#/components/responses/NotFound'

  /files/upload:
    post:
      summary: 上传 CSV 或 Excel 文件
      tags:
        - 文件
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 数据源名称
                file:
                  type: string
                  format: binary
                  description: CSV 或 Excel 文件
              required:
                - name
                - file
      responses:
        '201':
          description: 文件上传成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileDataSource'
        '400':
          description: 文件格式错误或大小超限
          content:
            application/json:
              schema:
                $ref: '#/components/responses/BadRequest'

  /files/{id}/preview:
    get:
      summary: 预览文件数据
      tags:
        - 文件
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 20
            description: 返回行数
        - name: offset
          in: query
          required: false
          schema:
            type: integer
            default: 0
            description: 分页偏移
      responses:
        '200':
          description: 文件数据预览
          content:
            application/json:
              schema:
                type: object
                properties:
                  total_rows:
                    type: integer
                  rows:
                    type: array
                    items:
                      type: object
                  columns:
                    type: array
                    items:
                      type: object

components:
  schemas:
    DataSource:
      type: object
      required:
        - id
        - name
        - type
        - status
        - created_at
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        type:
          type: string
          enum: ['postgresql', 'csv', 'excel']
        status:
          type: string
          enum: ['connected', 'disconnected', 'error']
        description:
          type: string
        created_at:
          type: string
          format: date-time
        last_tested_at:
          type: string
          format: date-time
        test_result:
          type: boolean

    FileDataSource:
      allOf:
        - $ref: '#/components/schemas/DataSource'
        - type: object
          properties:
            file_size:
              type: integer
            row_count:
              type: integer
            column_count:
              type: integer
            uploaded_at:
              type: string
              format: date-time

    CreatePostgresRequest:
      type: object
      required:
        - name
        - host
        - port
        - database
        - username
        - password
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 255
        host:
          type: string
          description: 数据库主机
        port:
          type: integer
          minimum: 1
          maximum: 65535
          default: 5432
        database:
          type: string
          description: 数据库名称
        username:
          type: string
          description: 用户名
        password:
          type: string
          description: 密码
          format: password
        ssl_enabled:
          type: boolean
          default: false

  responses:
    BadRequest:
      description: 请求格式错误
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
              details:
                type: string

    Unauthorized:
      description: 未授权
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string

    NotFound:
      description: 资源不存在
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
