openapi: 3.0.0
info:
  title: 数据库模式 API
  description: 获取和管理数据库模式的 API
  version: 1.0.0
servers:
  - url: /api
    description: API 基础路径

paths:
  /datasources/{id}/schema:
    get:
      summary: 获取数据源的完整模式
      tags:
        - 模式
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: refresh
          in: query
          required: false
          schema:
            type: boolean
            default: false
            description: 是否强制刷新缓存
      responses:
        '200':
          description: 完整的数据库模式
          content:
            application/json:
              schema:
                type: object
                properties:
                  tables:
                    type: array
                    items:
                      $ref: '#/components/schemas/Table'
                  total_tables:
                    type: integer
                  cached_at:
                    type: string
                    format: date-time
                  expires_at:
                    type: string
                    format: date-time
        '404':
          $ref: '#/components/responses/NotFound'
        '503':
          description: 数据源连接失败
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /datasources/{id}/schema/tables:
    get:
      summary: 获取表列表
      tags:
        - 模式
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: search
          in: query
          required: false
          schema:
            type: string
            description: 搜索表名
        - name: skip
          in: query
          required: false
          schema:
            type: integer
            default: 0
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 50
      responses:
        '200':
          description: 表列表
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                  tables:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        column_count:
                          type: integer
                        row_count:
                          type: integer

  /datasources/{id}/schema/tables/{table_name}:
    get:
      summary: 获取单个表的详细信息
      tags:
        - 模式
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: table_name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 表详细信息
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Table'

  /datasources/{id}/schema/tables/{table_name}/columns:
    get:
      summary: 获取表的列信息
      tags:
        - 模式
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: table_name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 列列表
          content:
            application/json:
              schema:
                type: object
                properties:
                  columns:
                    type: array
                    items:
                      $ref: '#/components/schemas/Column'

components:
  schemas:
    Table:
      type: object
      required:
        - name
        - columns
      properties:
        name:
          type: string
          description: 表名
        columns:
          type: array
          items:
            $ref: '#/components/schemas/Column'
        primary_keys:
          type: array
          items:
            type: string
          description: 主键列名
        foreign_keys:
          type: array
          items:
            $ref: '#/components/schemas/ForeignKey'
        row_count:
          type: integer
          description: 行数（统计值）
        indexes:
          type: array
          items:
            $ref: '#/components/schemas/Index'

    Column:
      type: object
      required:
        - name
        - data_type
        - nullable
      properties:
        name:
          type: string
          description: 列名
        data_type:
          type: string
          description: 数据类型 (integer, text, timestamp, float, boolean 等)
        nullable:
          type: boolean
          description: 是否可为 NULL
        default:
          description: 默认值
        precision:
          type: integer
          description: 数值精度
        scale:
          type: integer
          description: 小数位数
        is_primary_key:
          type: boolean
        is_unique:
          type: boolean
        description:
          type: string
          description: 列注释

    ForeignKey:
      type: object
      properties:
        constraint_name:
          type: string
        columns:
          type: array
          items:
            type: string
        referenced_table:
          type: string
        referenced_columns:
          type: array
          items:
            type: string

    Index:
      type: object
      properties:
        name:
          type: string
        columns:
          type: array
          items:
            type: string
        is_unique:
          type: boolean
        is_primary:
          type: boolean

  responses:
    NotFound:
      description: 资源不存在
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
