/**
 * Title Generation Utility
 *
 * Generates concise conversation titles from message content.
 * Uses client-side heuristics since the backend doesn't provide a title generation endpoint.
 */

/**
 * Generate a concise title from message content
 *
 * Strategy:
 * 1. Find the first sentence (ends with . ! or ?)
 * 2. If no sentence found, use first 50 characters
 * 3. Trim whitespace and normalize
 *
 * @param content - The message content to generate title from
 * @returns A concise title (max ~50 characters)
 *
 * @example
 * generateTitleFromContent("What is artificial intelligence?")
 * // returns "What is artificial intelligence?"
 *
 * @example
 * generateTitleFromContent("Tell me about the benefits of machine learning in healthcare applications")
 * // returns "Tell me about the benefits of machine learning in..."
 */
export const generateTitleFromContent = (content: string): string => {
  if (!content || content.trim().length === 0) {
    return 'New Conversation';
  }

  // Remove leading/trailing whitespace
  const trimmed = content.trim();

  // Find first sentence (ends with . ! or ?)
  const sentenceMatch = trimmed.match(/^[^.!?]*[.!?]/);

  if (sentenceMatch) {
    // Use the first sentence (including punctuation)
    const title = sentenceMatch[0].trim();

    // If sentence is too long, truncate it
    if (title.length > 60) {
      return title.substring(0, 57) + '...';
    }

    return title;
  }

  // No sentence terminator found, use first N characters
  const maxLength = 50;
  if (trimmed.length > maxLength) {
    return trimmed.substring(0, maxLength).trim() + '...';
  }

  return trimmed;
};

/**
 * Generate a title from multiple messages (conversation summary)
 *
 * Extracts the first message from the conversation and generates a title.
 * Useful for initializing thread titles when a conversation is created.
 *
 * @param messages - Array of messages in the conversation
 * @returns A concise title based on the first user message
 *
 * @example
 * const messages = [
 *   { role: 'user', content: 'How do I learn Python?' },
 *   { role: 'assistant', content: 'Here are some resources...' }
 * ];
 * generateTitleFromMessages(messages)
 * // returns "How do I learn Python?"
 */
export const generateTitleFromMessages = (
  messages: Array<{ role: string; content: string }>
): string => {
  // Find the first user message
  const firstUserMessage = messages.find((msg) => msg.role === 'user');

  if (firstUserMessage && firstUserMessage.content) {
    return generateTitleFromContent(firstUserMessage.content);
  }

  // Fallback if no user message found
  return 'New Conversation';
};

/**
 * Sanitize a title string for safe display
 * - Removes HTML special characters
 * - Normalizes whitespace
 * - Ensures reasonable length
 *
 * @param title - The title to sanitize
 * @returns Sanitized title
 *
 * @example
 * sanitizeTitle("What's the <best> way to learn?")
 * // returns "What's the best way to learn?"
 */
export const sanitizeTitle = (title: string): string => {
  return (
    title
      // Remove HTML entities and special characters
      .replace(/&[a-z]+;/gi, '')
      .replace(/[<>]/g, '')
      // Normalize whitespace
      .replace(/\s+/g, ' ')
      .trim()
      // Limit length
      .substring(0, 100)
  );
};

/**
 * Generate a default title when no content is available
 *
 * Generates titles like "Conversation 1", "Conversation 2", etc.
 *
 * @param index - 0-based index (optional, if not provided uses timestamp)
 * @returns Default conversation title
 *
 * @example
 * generateDefaultTitle(0) // returns "Conversation 1"
 * generateDefaultTitle(5) // returns "Conversation 6"
 * generateDefaultTitle() // returns "Conversation (timestamp)"
 */
export const generateDefaultTitle = (index?: number): string => {
  if (typeof index === 'number' && index >= 0) {
    return `Conversation ${index + 1}`;
  }

  const timestamp = new Date().toLocaleString('en-US', {
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  return `Conversation ${timestamp}`;
};

/**
 * Check if a title appears to be auto-generated
 *
 * Returns true for:
 * - "New Conversation"
 * - "Conversation 1", "Conversation 2", etc.
 * - Default format titles
 *
 * @param title - The title to check
 * @returns True if the title appears to be auto-generated
 *
 * @example
 * isAutoGeneratedTitle("New Conversation") // returns true
 * isAutoGeneratedTitle("Conversation 1") // returns true
 * isAutoGeneratedTitle("My Custom Title") // returns false
 */
export const isAutoGeneratedTitle = (title: string): boolean => {
  if (!title) return true;

  const autoGeneratedPatterns = [
    /^New Conversation$/i,
    /^Conversation \d+$/i,
    /^Conversation \(.*\)$/i,
  ];

  return autoGeneratedPatterns.some((pattern) => pattern.test(title));
};
